#!/bin/bash

# based on breadonpenguin's record script
# https://github.com/BreadOnPenguins/scripts/blob/master/record
# modified to work with my tmux centric workflow

eval "$(mise activate bash)"

screen_session="screencap"

if tmux has-session -t "$screen_session" 2>/dev/null; then
	tmux send-keys -t "$screen_session" C-c
	tmux kill-session -t "$screen_session"

	notify "closing recording"
else
	notify "starting recording"

	tmux new-session -d -s "$screen_session" \
		"ffmpeg -f avfoundation -r 60 -i 2:0 \"$HOME/video_$(date '+%a__%b%d__%H_%M_%S').mkv\""
fi
